

server:
  port: 9090


spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
  application:
    name: springboot-admin-client-test



management:
  endpoints:
    web:
      exposure:
        include: '*'


