server:
  port: 58080


#
spring:
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源连接
  datasource:
    url: jdbc:mysql://localhost:3306/kisso?characterEncoding=utf8&useSSL=false
    username: kisso
    password: kisso
    driver-class-name: com.mysql.jdbc.Driver

  # encoding
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true


kisso:
  config:
    sign-key: 9t0pwxGqQSkAb2JCs9Gd7n+dI5+A42iymo1C02r9C2RGiKStYln/IK2GkI/q0/gtoBouW80pJQNaSH6Tk2SFIQ==
    cookie-name: kisso
    cookie-domain: localhost
